services:
  postgres:
    image: postgres:16-alpine
    container_name: users-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  users-api:
    build:
      context: ./Users
      dockerfile: Users/Dockerfile
    container_name: users-api
    depends_on:
      - postgres
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Postgres: "Host=postgres;Port=5432;Database=users;Username=admin;Password=admin"
      Jwt__Issuer: "users"
      Jwt__Audience: "clients"
      Jwt__Key: "94b2cd921907d5dd977979e297a4e716"
      Jwt__ExpiresMinutes: "120"
    ports:
      - "5111:8080"

volumes:
  pgdata: