services:
  postgres:
    image: postgres:16-alpine
    container_name: users-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  neo4j:
    image: neo4j:5.22
    environment:
      - NEO4J_AUTH=neo4j/password
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data

  mongo:
    image: mongo:7
    container_name: tours-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:latest
    restart: unless-stopped
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017
      - ME_CONFIG_BASICAUTH=false
    ports:
      - "8081:8081"
    depends_on:
      - mongo

  users-api:
    build:
      context: ./Users
      dockerfile: Users/Dockerfile
    container_name: users-api
    depends_on:
      - postgres
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Postgres: "Host=postgres;Port=5432;Database=users;Username=admin;Password=admin"
      Jwt__Issuer: "users"
      Jwt__Audience: "clients"
      Jwt__Key: "94b2cd921907d5dd977979e297a4e716"
      Jwt__ExpiresMinutes: "120"
    ports:
      - "5111:8080"

  blog-followers:
    build:
      context: ./social
      dockerfile: Dockerfile
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
    ports:
      - "8082:8082"
    depends_on:
      - neo4j

  tours-api:
    build:
      context: ./tours
      dockerfile: Dockerfile
    container_name: tours-api
    depends_on:
      - mongo
    restart: unless-stopped
    environment:
      PORT: "8083"
      MONGO_URI: "mongodb://mongo:27017/tours"
    ports:
      - "8083:8083"

  gateway:
    image: nginx:alpine
    container_name: api-gateway
    depends_on:
      - users-api
      - tours-api
      - blog-followers
    ports:
      - "8080:8080"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  pgdata:
  neo4j_data:
  mongo_data: